export const youtubeUrlList = [
    "https://www.youtube.com/embed/D7tv_QOlMBk",
    "https://www.youtube.com/embed/yCzIEXBrFOs",
    "https://www.youtube.com/embed/cjifVf9XKm0",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/iSuZ61db9F8",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
    "https://www.youtube.com/embed/ZmUEw4lWRBk",
];